### ISSUE TITLE
automad and dates

### ISSUE THREAD

**Issue by demlak** [B-iggy/old-website-automad#1]
hi,
currently im also playing with automad.. since im also interested in dates and times when a page is edited.. i found your text here on guithub.. maybe you can give me a hint, how to edit the core to get this feature..
this is one of my wirst steps for using automad as a blog.. 
next step: building a theme that fitts my needs.. including showing the date =)

thx in advance

**Comment by B-iggy** [comment]
Hey demlak,
I guess you are referring to my last point here? https://github.com/B-iggy/old-website-automad#gui

It wasn't so comfortable as in wordpress at all. I had to set the date automatically in a global variable; but in the GUI at least which I could display in my theme :)

To have this feature you need to change following things:
https://github.com/B-iggy/old-website-automad/commit/b3b9bd13ac81a4e030a9a1d94a96af1f8c6420ad
Go with "date" (CTRL+F) through the page and you see the needed changes. 

Please keep in mind that the author is refactoring the code from time to time:
https://bitbucket.org/marcantondahmen/automad/commits/all

If you need more help let me just know.

**Comment by demlak** [comment]
thx a lot
i´ll take a look at this.. seems to be more complicated as i thought..

and your hint about the changes by the author make me think more about it.. =(

**Comment by B-iggy** [comment]
It's seems a lot but easy after some time. After all it isn't good anyways because if a update comes all your changes are lost. The disadvantage on operating on the core.

----------
Kein Problem, meins ja auch :) Ich weiß nicht warum, aber leider arbeitet der Marc allein am Projekt. Würde er da offener sein hätte Automad echt Potential. So verpasst er leider den Zug. Im Moment sprießen Flat CMS aus dem Boden wie Pilze. ;)

**Comment by demlak** [comment]
ich hab auch ein wenig im web quer gelesen.. es gibt wohl bedarf für eine platform zum austausch.. 
vieleicht könnte man ja auch einfach ein forum aufsetzen.. zum sich austauschen.. es muss ja nicht vom developer kommen.. man könnte ja einfach so was starten..

ich selbst bin halt kein coder.. und frickel mir alles aus schnippseln zusammen.. ein gewisses grundverständnis is da.. aber mehr auch nicht...

ich bin noch am überlegen, ob man nicht in irgendeinem konzept die extensions nutzen könnte, um das mit der zeit zu realisieren... momentan ist ja eine extension für das jahr mit integriert.. es sollte ein leichtes sein, eine weitere für komplettes datum + uhrzeit zu implementieren.. vieleicht ist es dann auch einfacher dies im core mit zu integrieren.. bzw. vieleicht übrnimmt marc das dann auch?

**Comment by demlak** [comment]
p.s. ich bin mal so dreist.. und hab jetzt einfach mal einen channel auf freenode aufgemacht.. 
webchat: http://webchat.freenode.net/?channels=%23automad&uio=d4

direktlink für irc clienten: irc://chat.freenode.net/automad

**Comment by B-iggy** [comment]
Das wäre eine Idee und könnten wir sicher machen. Gibt sicher genügend Forum Web Tools.

Meine letzten Baustellen an Automad war die GUI. Da steckt noch ne Menge Optimierungsbedarf drin. Allein vom Design her. Ansonsten war es doch recht lustig.
Zu Wordpress bin ich wegen meinem zukünftigen Business gewechselt, bzw. mehr Erfahrung damit sammeln.

Das war auch erst meine Idee, diese Extension anzuzapfen, bzw. die, die sagt, wann du dich das letzte Mal in der GUI eingeloggt hast. Vielleicht ist da mehr drin. Ansonsten eben eine Erweiterung schreiben, wie ich es rudimentär mit SEO gemacht habe ;)

**Comment by demlak** [comment]
falls du den webchat nutzt.. der pingt manchmal aus.. ka ob du grad noch online biste.. 

btw.. dieser thread hier kann wohl gelöscht werden =)
